#!/usr/bin/env node
// Regenerates agents-index.md (repo root) by scanning every division folder for
// agent persona markdown files and pulling name/description/emoji from their
// YAML frontmatter. The index is the catalog the agency-agents skill (SKILL.md)
// reads to match a request to an agent. Run from anywhere: node scripts/build-index.mjs
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), ".."); // scripts -> repo root
const outFile = join(repoRoot, "agents-index.md");

const divisions = JSON.parse(
  readFileSync(join(repoRoot, "divisions.json"), "utf8")
).divisions;

// Pull single-line scalar values out of YAML frontmatter (the block between the
// first two `---` fences). Splits on the first ": " so values containing colons survive.
function frontmatter(md) {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const out = {};
  for (const line of m[1].split(/\r?\n/)) {
    const i = line.indexOf(": ");
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    let val = line.slice(i + 2).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

let total = 0;
const sections = [];

for (const [dir, meta] of Object.entries(divisions)) {
  let files;
  try {
    files = readdirSync(join(repoRoot, dir))
      .filter((f) => f.endsWith(".md"))
      .sort();
  } catch {
    continue;
  }
  if (files.length === 0) continue;

  const rows = [];
  for (const file of files) {
    const path = `${dir}/${file}`;
    const fm = frontmatter(readFileSync(join(repoRoot, path), "utf8"));
    const name = fm.name || file.replace(/\.md$/, "");
    const emoji = fm.emoji ? fm.emoji + " " : "";
    const desc = (fm.description || "").replace(/\s+/g, " ").trim();
    rows.push(`- ${emoji}**${name}** — \`${path}\`\n  ${desc}`);
    total++;
  }

  sections.push(`## ${meta.label} (${rows.length})\n\n${rows.join("\n")}`);
}

const header = `# The Agency — Agent Index

Auto-generated by \`scripts/build-index.mjs\`. **Do not edit by hand** — re-run the
generator after adding or renaming agents.

${total} agents across ${sections.length} divisions. Each entry lists the agent's
display name, the repo-relative path to its persona file (read this file to adopt
the agent), and a one-line description for matching a request to the right agent.

`;

writeFileSync(outFile, header + sections.join("\n\n") + "\n", "utf8");
console.log(`Wrote ${outFile}: ${total} agents, ${sections.length} divisions.`);
